# Generated by Django 6.0 on 2026-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reorder',
            name='material',
        ),
        migrations.RemoveField(
            model_name='reorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='vendors',
        ),
        migrations.DeleteModel(
            name='VendorBill',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='reorder_id',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('client_created', 'Client Created'), ('client_updated', 'Client Updated'), ('client_deleted', 'Client Deleted'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('payment_recorded', 'Payment Recorded'), ('material_created', 'Material Created'), ('material_updated', 'Material Updated'), ('material_deleted', 'Material Deleted'), ('invoice_created', 'Invoice Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(default='Cosmo Enterprises', max_length=100),
        ),
        migrations.DeleteModel(
            name='Reorder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
