# Generated by Django 6.0 on 2026-06-01 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_reorder_material_remove_reorder_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces (min 2 characters).', regex='^[a-zA-Z\\s]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +91 98765 43210).', regex='^\\+?[\\d\\s\\-\\(\\)]{10,15}$')]),
        ),
    ]
