# Generated by Django 6.0 on 2026-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
