# Generated by Django 6.0 on 2026-06-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_invoice_stripe_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_address',
            field=models.TextField(default='Textile Area, Karachi, Pakistan'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
